# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build production CI

on:
  push:
    branches: [ "production" ]

jobs:
  build:

    runs-on: windows-latest
    

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: $env:CI=$false; npm run package
    - run: tar -a -c -f build.zip ./out
    # - uses: vimtor/action-zip@v1
    #   with:
    #     files: ./out
    #     dest: result.zip

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.TOKEN_SECRET }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Production Build"
        files: build.zip
